package com.waci.erp.config;

/**
 * Holds  key names of the environment variables used throughout the MS
 */
public interface EnvironmentConstants {
    String KAFKA_BOOTSTRAP_SERVERS_CONFIG = "KAFKA_BOOTSTRAP_SERVERS_CONFIG";
    String KAFKA_GROUP_ID = "1";
    String KAFKA_POLL_INTERVAL_MS = "KAFKA_POLL_INTERVAL_MS";
    String KAFKA_GENERAL_ERROR_CHANNEL = "KAFKA_GENERAL_ERROR_CHANNEL";
    String KAFKA_EXTERNAL_SYSTEM_INTERNAL_SERVER_ERROR_CHANNEL = "KAFKA_EXTERNAL_SYSTEM_INTERNAL_SERVER_ERROR_CHANNEL";
    String KAFKA_UNEXPECTED_API_RESPONSE_CHANNEL = "KAFKA_UNEXPECTED_API_RESPONSE_CHANNEL";
    String KAFKA_EXTERNAL_SYSTEM_DOWN_CHANNEL = "KAFKA_EXTERNAL_SYSTEM_DOWN_CHANNEL";


}